### PR TITLE
Interfaces

### PR DESCRIPTION
**Pull request by mKroogz**
git fetch --all
git checkout interfaces
look at it
no tests yet

### CODE REVIEW

**Comment by keithrpotempa** [comment]
👍 
We were all there and loved every moment of it.

**Comment by sncandiani** [comment]
Other than the strange animal/pycache error on my part, it looks like we have all the files that we went through together.

**Comment by alyssa-nycum-imprivata** [comment]
All looks good! And I'm glad Keith is no longer decapitated.

**Comment by MattCrook** [comment]
Looks good

**Pull request merged**
