### PR TITLE
Mc menu options

### PR DESCRIPTION
**Pull request by MattCrook**
`git fetch --all`
`git checkout MC-menu-options`

If you run the actual program (from the `index.py`) should show all Biomes, when you select one it should show up in the report.

### CODE REVIEW

**Comment by sncandiani** [comment]
I annexed each one and it looks like it works.

**Comment by alyssa-nycum-imprivata** [comment]
No errors - added all 6 biomes. Great job!

**Comment by mKroogz** [comment]
I love it.  The title is bomb.com

**Comment by keithrpotempa** [comment]
👍 Works as expected! Solid job

**Pull request merged**
