### PR TITLE
Animals

### PR DESCRIPTION
**Pull request by alyssa-nycum-imprivata**
git fetch --all
git checkout animals
check out code for animals: 1) private variables 2) use of interfaces 3) feed method that will tie to the actions menu

### CODE REVIEW

**Comment by keithrpotempa** [comment]
animal.py
- Line 14: `{self. species}` should be `{self.__species}` or `{self.species}`

DRY Suggestions:
- It seems a better approach to have getters for "universal" animal private properties __species, __min_release_age, __prey in the Animal parent class rather than in the child classes
- You could move the feed method of the animal children to the Animal parent with something like `print(f"The {self.species} ate {prey} for a meal")`
- You could move the string methods (__str__) of the animal children to the Animal parent with something like: `return f"{self.species} {self.id}`

**Comment by keithrpotempa** [comment]
Perfect! Thanks for powering through, Alyssa.

**Comment by sncandiani** [comment]
Thoroughly reviewed as a group, looks good to me!

**Comment by mKroogz** [comment]
Awesome everything is looking good on the biome test side :D

**Pull request merged**
