### PR TITLE
Kp plants

### PR DESCRIPTION
**Pull request by keithrpotempa**
1. `git fetch --all`
2. `git checkout kp-plants`
3. Take a look at everything in the `/plants/` folder:

- Plant parent class
- the various child classes
- the __init__ package

### CODE REVIEW

**Comment by alyssa-nycum-imprivata** [comment]
Look great!

**Comment by MattCrook** [comment]
Looks good to me!

**Comment by sncandiani** [comment]
After thorough testing, it looks great!

**Comment by keithrpotempa** [comment]
Thanks, y'all!

**Comment by mKroogz** [comment]
You're awesome keith!  Learned a lot from how we all approached this haha!

**Pull request merged**
