### PR TITLE
README

### PR DESCRIPTION
**Pull request by sncandiani**
1. Git checkout master 
2. Git fetch --all 
3. Git checkout sc-README
4. Check the README for proper explanation of the process of navigating the application.

### CODE REVIEW

**Comment by keithrpotempa** [comment]
Here's an easier way to look at the readme without having to pull anything down:
https://github.com/nss-day-cohort-38/keahua-arboretum-firefly-tower/tree/sc-README

Scroll down and look at the readme there.

**Comment by mKroogz** [comment]
You changed river animal cap to 1 but otherwise lookin good 😛

**Comment by keithrpotempa** [comment]
How about adding our names and links to the top?

Something like:

A group project by:

- [Sofia Candiani](https://github.com/sncandiani)
- [Matthew Kroeger](https://github.com/mKroogz)
- [Matt Crook](https://github.com/MattCrook)
- [Keith Potempa](https://github.com/keithrpotempa)

**Comment by alyssa-nycum-imprivata** [comment]
Looks great! Can you make one edit under the animal feeding menu? It says:

If the user chooses 3 from the main menu, then they should see the following menu, with the plants listed.

**plants needs to be changed to animals (this wasn't your typo - it was in the original repo)

**Comment by keithrpotempa** [comment]
👍  Thanks for making this magic happen!

**Comment by alyssa-nycum-imprivata** [comment]
Beautiful!

**Comment by mKroogz** [comment]
Looks really nice!!

**Pull request merged**
