### PR TITLE
Release Animal

### PR DESCRIPTION
**Pull request by sncandiani**
1. Git fetch --all 
2. Git checkout sc-releaseAnimal1
3. Test for ability to release animals into their proper habitats, habitats that are not applicable should not show up at all

### CODE REVIEW

**Comment by keithrpotempa** [comment]
A suggestion: if there are no environments to release an animal, there should be a different message than "Choose environment to release... >" that loops back to... the Release animal menu?

**Comment by keithrpotempa** [comment]
That fixed it!

**Comment by alyssa-nycum-imprivata** [comment]
Looks great Sofia!!

**Comment by mKroogz** [comment]
Looks awesome :)

**Pull request merged**
