### PR TITLE
Kp tester

### PR DESCRIPTION
**Pull request by keithrpotempa**
The following changes were made to environments during a live share party with the entire group participating:
- change to if/else statements with a print error messages
- call the get plant and get animal count methods
- remove self from super().__init__(self), biome age check. 

These changes were made while running tester.py, which was created and is now successfully running through every environment, attempting to add every plant to that environ. 

You can run it in terminal from project's root folder:
`python tester.py`

### CODE REVIEW

**Comment by sncandiani** [comment]
Looks great, amazing job with the tester!!

**Comment by mKroogz** [comment]
Was fun coding this out :D

**Comment by keithrpotempa** [comment]
We did it *together*!

**Comment by alyssa-nycum-imprivata** [comment]
Looks great! The Tester page is amazing!!

**Comment by keithrpotempa** [comment]
- "Any key to continue" is not quite working
- Cannot check if animals are showing up in the report yet, since we don't have the ability to add them yet. But we can circle back to that at a later point.

**Comment by keithrpotempa** [comment]
👍

**Pull request merged**
