### PR TITLE
Kp plant menu

### PR DESCRIPTION
**Pull request by keithrpotempa**
add_plant action created per the exercise prerequisites

Changes to environment child classes:
- test_plant methods added

Test process:
1. `git checkout master`
2. `git fetch --all`
3. `git checkout kp-plant-menu`
4. `python index.py`
5. Build some environment instances with "Secret Seven"
6. Select option 4 to move to add plants
7. Only environments appropriate to the plant should display
8. You can verify the addition of the plant by checking the report with option 5 at the main menu (there will be more than one of that plant in some instance somewhere)

EXTRA THANKS TO MATT K for help on commit 58b64d8 getting the plant tests working

### CODE REVIEW

**Comment by mKroogz** [comment]
Everything looks awesome!  Love accidentally hitting a stretch goal with you hahaha

**Comment by sncandiani** [comment]
Everything looks great. Only thing is I would add in a feature that displays a message if they have not yet added habitats.

**Comment by alyssa-nycum-imprivata** [comment]
Looks great! String methods on environments just need to be added for a cleaner look.

**Comment by keithrpotempa** [comment]
> Everything looks great. Only thing is I would add in a feature that displays a message if they have not yet added habitats.

I fixed this so there's a prompt to choose a new plant that loops you back to the same menu.

**Pull request merged**
