### PR TITLE
Initial biomes

### PR DESCRIPTION
**Pull request by sncandiani**
1. Git fetch --all 
2. Git checkout scmk-environments 1
3. Check environments folder for all biomes and environment parent class and whether biomes have proper checking qualifications

### CODE REVIEW

**Comment by keithrpotempa** [comment]
My only comment: in the AttributeError messages for add_plant and add_animal, you could utilizse {self.plant_cap} or {self.animal_cap} or have the message be generic (like Matt's)

**Comment by keithrpotempa** [comment]
👍

**Comment by mKroogz** [comment]
Looking good!  Can't wait to test!

**Comment by alyssa-nycum-imprivata** [comment]
Looks good!

**Pull request merged**
